Migratation to jina3
jina-ai/executor-text-clip-encoder pull request #4
Opened 2022-01-24 12:55 UTC by samsja

2022-01-25 08:45 UTC, samsja commented
DO NOT MERGE before 
* merging https://github.com/jina-ai/executor-text-clip-encoder/pull/5 into main
* changing back the cicd to point to the master branch of the workflow-executors repo

2022-01-28 08:57 UTC, JoanFM requested changes

2022-01-28 08:57 UTC, JoanFM commented on main.py
> +from clip_text import CLIPTextEncoder
why do u add a main? pls remove

2022-02-01 08:44 UTC, JoanFM approved these changes

2022-02-01 15:35 UTC, samsja commented
https://github.com/jina-ai/internal-tasks/issues/379

2022-02-11 08:09 UTC, mapleeit commented
Seems we should git ignore `.idea` and `__pycache__`?

2022-02-11 11:01 UTC, merged